### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by Danee-wawawa** [CXH-Research/IRFormer#1]
Hi, thank you for your work. 
What is the folder structure for TRAIN_DIR and VAL_DIR? How to construct visible data and infrared data?
Looking forward to your answer~

**Comment by xuhangc** [comment]
Hi, the folder structure of dataset is shown below.
```
.
└── dataset/
    ├── TRAIN_DIR /
    │   ├── vis_img
    │   └── ir_img
    └── VAL_DIR/
        ├── vis_img
        └── ir_img
```

As for the data, you may download from the sources mentioned in the paper.

**Comment by Danee-wawawa** [comment]
OK, thank you~
Do the aligned images in the "vis_img" and "ir_img" folders need to be named with the same name?

**Comment by xuhangc** [comment]
> OK, thank you~ Do the aligned images in the "vis_img" and "ir_img" folders need to be named with the same name?

In this dataloader yes, but you can change the code to make it fit to other naming conventions.

**Comment by Danee-wawawa** [comment]
OK, thank you~
