### ISSUE TITLE
咨询一下有没有开源的预训练权重

### ISSUE THREAD

**Issue by LT1st** [CXH-Research/IRFormer#3]
您好，请问有开源预训练权重值嘛？另外想问问Infragan的复现怎么做的？我复现哪篇论文时候，发现效果很差，即使使用700epoch训练（FLIR数据集）。

**Comment by knavecoder** [comment]
我们复现出来的效果也很差

**Comment by knavecoder** [comment]
关于预训练权重，目前我们项目我们还在工作，暂时不开源权重
